/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'

import React from 'react'
import CssBaseline from '@mui/material/CssBaseline'
import Container from '@mui/material/Container'
import Sidebar from '../components/Sidebar'
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

const sidebarItems = [
  'Item 1',
  'Item 2',
  'Item 3',
  'Item 4',
  'Item 5',
  'Item 6',
  'Item 7',
  'Item 8',
  'Item 9',
  'Item 10',
  'Item 11',
  'Item 12',
  'Item 13',
]

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry>
          <div style={{ display: 'flex' }}>
            <CssBaseline />
            <Sidebar />
            <Navbar />
            <Container>{children}</Container>
          </div>
        </ThemeRegistry>
      </body>
    </html>
  )
}
